<form action="<?= $block->getUrl('mod8/index/save') ?>" method="post">
    <label for="first_name">First Name:</label>
    <input type="text" id="first_name" name="first_name" required/>

    <label for="last_name">Last Name:</label>
    <input type="text" id="last_name" name="last_name" required/>

    <label for="email_id">Email ID:</label>
    <input type="email" id="email_id" name="email_id" required/>

    <button type="submit">Submit</button>
</form>
